### PR TITLE
Change timestamp server

### PR DESCRIPTION
**Pull request by Lnaden**
See conda-forge/docker-images#69 for why

Related to #13 
cc @jchodera

### CODE REVIEW

**Comment by Lnaden** [comment]
This change is a copy of the linked Conda-Forge change from above

**Comment by jchodera** [comment]
Thanks!

**Comment by jchodera** [comment]
@Lnaden : This also failed because we pin `conda-build`:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda-build==2.1.17 -> conda[version='>=4.1,<4.4']
  - conda[version='>=4.5.11']
Use "conda info <package>" to see the dependencies for each package.
```
Any more ideas, or do we have to embrace the awful path of figuring out how to upgrade `conda-build`?

**Comment by Lnaden** [comment]
I pushed another change to the branch which should get the conda pinned in correctly, see #15 

I already merged it to trigger the build

**Comment by jchodera** [comment]
Qapla'!

Rebuilding the separate CUDA images now.

**Pull request merged**
